services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"   # management UI
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      retries: 5

  delivery:
    build: ./delivery-service
    ports:
      - "5000:5000"

  rider:
    build: ./rider-service
    ports:
      - "5001:5001"

  assign_delivery:
    build: ./assign-delivery-service
    ports:
      - "5002:5002"
    env_file:
      - ./assign-delivery-service/.env
    environment:
      DELIVERY_URL: http://delivery:5000
      RIDER_URL: http://rider:5001
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      rabbitmq:
        condition: service_healthy
      delivery:
        condition: service_started
      rider:
        condition: service_started

  complete_delivery:
    build: ./complete-delivery-service
    ports:
      - "5004:5004"
    environment:
      DELIVERY_URL: http://delivery:5000
      RIDER_URL:    http://rider:5001
      ORDER_URL:    http://order:5003   # P3's service
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - rabbitmq
      - delivery
      - rider

  amazon_s3_wrapper:
    build: ./amazon-s3-wrapper
    ports:
      - "5020:5020"

  telegram_wrapper:
    build: ./telegram_wrapper
    ports:
      - "5012:5012"
    env_file:
      - ./telegram_wrapper/.env
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      PATIENT_SERVICE_URL: http://patient-service:5030
    depends_on:
      rabbitmq:
        condition: service_healthy

  tracking-service:
    build: ./tracking-service
    ports:
      - "5050:5050"
    environment:
      DELIVERY_SERVICE_URL: http://delivery:5000
    depends_on:
      - delivery